# Dense neural network to perform Logistic regression task  



### Atharva Mankame 21BAI1780



In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [24]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [25]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]
 [    35  25000]
 [    35  50000]
 [    42  73000]
 [    47  49000]
 [    59  29000]
 [    49  65000]
 [    45 131000]
 [    31  89000]
 [    46  82000]
 [    47  51000]
 [    26  15000]
 [    60 102000]
 [    38 112000]
 [    40 107000]
 [    42  53000]
 [    35  59000]
 [    48  41000]
 [    48 134000]
 [    38 113000]
 [    29 148000]
 [    26  15000]
 [    60  42000]
 [    24  19000]
 [    42 149000]
 [    46  96000]
 [    28  59000]
 [    39  96000]
 [    28  89000]
 [    41  72000]
 [    45  26000]
 [    33  69000]
 [    20  82000]
 [    31  74000]
 [    42  80000]
 [    35  72000]
 [    33 149000]
 [    40  71000]
 [    51 146000]
 [    46  79000]
 [    35  75000]
 [    38  51000]
 [    36  75000]
 [    37  78000]
 [    38  61000]
 [    60 108000]
 [    20  82000]
 [    57  74000]
 [    42  65000]
 [    26  8000

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 

In [28]:
ann = tf.keras.models.Sequential()

In [29]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=128, activation='relu'))
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
# Add a single dense layer for logistic regression
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid', input_dim=X_train.shape[1]))

In [30]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [31]:
ann.fit(X_train, y_train, batch_size=32, epochs=100, verbose=1)

Epoch 1/100
10/10 [==============================] - 2s 4ms/step - loss: 0.6602 - accuracy: 0.7333
Epoch 2/100
10/10 [==============================] - 0s 4ms/step - loss: 0.5453 - accuracy: 0.8633
Epoch 3/100
10/10 [==============================] - 0s 3ms/step - loss: 0.4060 - accuracy: 0.8600
Epoch 4/100
10/10 [==============================] - 0s 3ms/step - loss: 0.3135 - accuracy: 0.8800
Epoch 5/100
10/10 [==============================] - 0s 3ms/step - loss: 0.2665 - accuracy: 0.9033
Epoch 6/100
10/10 [==============================] - 0s 3ms/step - loss: 0.2488 - accuracy: 0.9000
Epoch 7/100
10/10 [==============================] - 0s 3ms/step - loss: 0.2392 - accuracy: 0.9100
Epoch 8/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2378 - accuracy: 0.9100
Epoch 9/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2346 - accuracy: 0.9067
Epoch 10/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2312 - accuracy: 0.9100
Epoch 11/

In [32]:
# Make predictions
y_pred = ann.predict(X_test)

# Set print options for precision
np.set_printoptions(precision=2)

# Print the predicted and actual values
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(y_pred, y_test)

4/4 [==============================] - 0s 3ms/step
[[2.02e-03]
 [2.13e-03]
 [1.96e-02]
 [4.62e-04]
 [2.85e-04]
 [3.53e-09]
 [5.91e-08]
 [9.66e-01]
 [4.15e-09]
 [9.33e-01]
 [3.99e-06]
 [2.24e-06]
 [2.61e-03]
 [2.34e-01]
 [2.67e-07]
 [8.69e-01]
 [1.79e-01]
 [1.01e-07]
 [8.32e-01]
 [3.73e-06]
 [1.78e-04]
 [8.75e-01]
 [1.30e-02]
 [7.28e-01]
 [4.28e-10]
 [8.58e-01]
 [3.08e-04]
 [2.29e-04]
 [9.82e-03]
 [1.21e-02]
 [8.51e-07]
 [2.26e-01]
 [9.60e-01]
 [1.87e-03]
 [1.30e-07]
 [3.43e-10]
 [7.26e-07]
 [4.29e-05]
 [8.63e-07]
 [9.84e-01]
 [1.52e-04]
 [1.43e-02]
 [7.89e-05]
 [2.78e-06]
 [7.86e-01]
 [1.57e-06]
 [2.45e-01]
 [9.68e-01]
 [6.83e-09]
 [9.23e-01]
 [9.09e-01]
 [2.78e-06]
 [8.87e-04]
 [8.68e-01]
 [9.97e-01]
 [8.54e-01]
 [3.81e-04]
 [1.82e-05]
 [9.96e-01]
 [1.18e-10]
 [2.16e-07]
 [9.35e-01]
 [2.99e-08]
 [7.82e-01]
 [1.13e-11]
 [9.97e-01]
 [1.33e-05]
 [1.57e-06]
 [4.70e-03]
 [1.14e-01]
 [9.71e-01]
 [2.99e-02]
 [5.41e-08]
 [8.54e-01]
 [1.81e-04]
 [2.91e-08]
 [1.81e-01]
 [2.33e-02]
 [9.87e-01]
 

In [33]:
import pandas as pd

# Create a DataFrame with predicted and actual values
df = pd.DataFrame({'Predicted': y_pred.flatten(), 'Actual': y_test})

# Display the DataFrame
print(df)


       Predicted  Actual
0   2.023857e-03       0
1   2.131709e-03       0
2   1.964970e-02       0
3   4.622824e-04       0
4   2.852646e-04       0
..           ...     ...
95  9.883601e-04       1
96  1.241875e-07       0
97  9.903872e-01       1
98  8.612407e-01       1
99  7.677364e-01       1

[100 rows x 2 columns]


In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = ann.predict(X_test)
y_predb = (y_pred > 0.5)

4/4 [==============================] - 0s 3ms/step


In [35]:
cm = confusion_matrix(y_test, y_predb)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[64  4]
 [ 3 29]]


In [36]:
acc = accuracy_score(y_test, y_predb)
print("Accuracy:", acc)

Accuracy: 0.93


In [37]:
df_comparison_binary = pd.DataFrame({'y_pred_binary': y_predb.flatten(), 'y_test': y_test})
print(df_comparison_binary)

    y_pred_binary  y_test
0           False       0
1           False       0
2           False       0
3           False       0
4           False       0
..            ...     ...
95          False       1
96          False       0
97           True       1
98           True       1
99           True       1

[100 rows x 2 columns]
