# Dense neural network to perform Linear regression task  

### Atharva Mankame 21BAI1780

In [11]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [12]:
dataset = pd.read_csv('50_Startups_dataset.csv')
dataset

Unnamed: 0  R&D Spend  Administration  Marketing Spend       State  \
0            0  165349.30       136897.90        471784.20    New York   
1            1  162597.80       151377.69        443898.63  California   
2            2  153441.61       101145.65        407934.64     Florida   
3            3  144372.51       118671.95        383199.72    New York   
4            4  142107.44        91391.87        366168.52     Florida   
5            5  131877.00        99814.81        362861.46    New York   
6            6  134615.56       147198.97        127716.92  California   
7            7  130298.23       145530.16        323876.78     Florida   
8            8  120542.62       148719.05        311613.39    New York   
9            9  123334.98       108679.27        304981.72  California   
10          10  101913.18       110594.21        229161.05     Florida   
11          11  100672.06        91790.71        249744.65  California   
12          12   93863.85       127320.48        249839.54     Florida   
13          13   91992.49       135495.17        252665.03  California   
14          14  119943.34       156547.52        256513.02     Florida   
15          15  114523.71       122616.94        261776.33    New York   
16          16   78013.21       121597.65        264346.16  California   
17          17   94657.26       145077.68        282574.41    New York   
18          18   91749.26       114175.89        294919.67     Florida   
19          19   86419.80       153514.21             0.10    New York   
20          20   76253.96       113867.40        298664.57  California   
21          21   78389.57       153773.53        299737.39    New York   
22          22   73994.66       122782.85        303319.36     Florida   
23          23   67532.63       105751.13        304768.83     Florida   
24          24   77044.11        99281.44        140574.91    New York   
25          25   64664.81       139553.26        137962.72  California   
26          26   75328.97       144136.08        134050.17     Florida   
27          27   72107.70       127864.65        353183.91    New York   
28          28   66051.62       182645.66        118148.30     Florida   
29          29   65605.58       153032.16        107138.48    New York   
30          30   61994.58       115641.38         91131.34     Florida   
31          31   61136.48       152702.02         88218.33    New York   
32          32   63408.96       129219.71         46085.35  California   
33          33   55494.05       103057.59        214634.91     Florida   
34          34   46426.17       157694.02        210797.77  California   
35          35   46014.12        85047.54        205517.74    New York   
36          36   28663.86       127056.31        201126.92     Florida   
37          37   44070.05        51283.24        197029.52  California   
38          38   20229.69        65948.03        185265.20    New York   
39          39   38558.61        82982.19        174999.40  California   
40          40   28754.43       118546.15        172795.77  California   
41          41   27893.02        84710.87        164470.81     Florida   
42          42   23641.03        96189.73        148001.21  California   
43          43   15505.83       127382.40         35534.27    New York   
44          44   22177.84       154806.24         28334.82  California   
45          45    1000.33       124153.14          1904.03    New York   
46          46    1315.56       115816.31        297114.56     Florida   
47          47       0.10       135427.02             0.10  California   
48          48     542.15        51743.25             0.10    New York   
49          49       0.10       116983.90         45173.16  California   

       Profit  
0   192261.93  
1   191792.16  
2   191050.49  
3   182902.09  
4   166188.04  
5   156991.22  
6   156122.61  
7   155752.70  
8   152211.87  
9   149760.06  
10  146122.05  
11  144259.50  
12  141585.62  
13  1

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])

In [14]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
X

array([[0.0000000e+00, 1.6534930e+05, 1.3689790e+05, 4.7178420e+05,
        2.0000000e+00],
       [1.0000000e+00, 1.6259780e+05, 1.5137769e+05, 4.4389863e+05,
        0.0000000e+00],
       [2.0000000e+00, 1.5344161e+05, 1.0114565e+05, 4.0793464e+05,
        1.0000000e+00],
       [3.0000000e+00, 1.4437251e+05, 1.1867195e+05, 3.8319972e+05,
        2.0000000e+00],
       [4.0000000e+00, 1.4210744e+05, 9.1391870e+04, 3.6616852e+05,
        1.0000000e+00],
       [5.0000000e+00, 1.3187700e+05, 9.9814810e+04, 3.6286146e+05,
        2.0000000e+00],
       [6.0000000e+00, 1.3461556e+05, 1.4719897e+05, 1.2771692e+05,
        0.0000000e+00],
       [7.0000000e+00, 1.3029823e+05, 1.4553016e+05, 3.2387678e+05,
        1.0000000e+00],
       [8.0000000e+00, 1.2054262e+05, 1.4871905e+05, 3.1161339e+05,
        2.0000000e+00],
       [9.0000000e+00, 1.2333498e+05, 1.0867927e+05, 3.0498172e+05,
        0.0000000e+00],
       [1.0000000e+01, 1.0191318e+05, 1.1059421e+05, 2.2916105e+05,
        1.00

In [16]:
y

array([192261.93, 191792.16, 191050.49, 182902.09, 166188.04, 156991.22,
       156122.61, 155752.7 , 152211.87, 149760.06, 146122.05, 144259.5 ,
       141585.62, 134307.45, 132602.75, 129917.14, 126993.03, 125370.47,
       124267.  , 122776.96, 118474.13, 111313.12, 110352.35, 108734.09,
       108552.14, 107404.44, 105733.64, 105008.41, 103282.48, 101004.74,
        99937.69,  97483.66,  97427.94,  96779.02,  96712.9 ,  96479.61,
        90708.29,  89949.24,  81229.16,  81005.86,  78240.01,  77798.93,
        71498.59,  69759.08,  65200.43,  64926.18,  49490.85,  42559.83,
        35673.51,  14681.5 ])

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
ann = tf.keras.models.Sequential()

In [19]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=128, activation='relu'))
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
# ann.add(tf.keras.layers.Dense(units=1))
ann.add(tf.keras.layers.Dense(units=1, activation='linear'))

In [20]:
ann.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), loss='mean_squared_error', metrics=['mean_absolute_error'])

In [21]:
ann.fit(X_train, y_train, batch_size = 64, epochs = 200, verbose = 1)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 13362653184.0000 - mean_absolute_error: 108583.0234
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 13263295488.0000 - mean_absolute_error: 108174.2266
Epoch 3/200
1/1 [==============================] - 0s 13ms/step - loss: 13165211648.0000 - mean_absolute_error: 107768.8984
Epoch 4/200
1/1 [==============================] - 0s 13ms/step - loss: 13067611136.0000 - mean_absolute_error: 107364.3750
Epoch 5/200
1/1 [==============================] - 0s 13ms/step - loss: 12970049536.0000 - mean_absolute_error: 106958.1250
Epoch 6/200
1/1 [==============================] - 0s 14ms/step - loss: 12872078336.0000 - mean_absolute_error: 106548.8516
Epoch 7/200
1/1 [==============================] - 0s 18ms/step - loss: 12774085632.0000 - mean_absolute_error: 106138.0156
Epoch 8/200
1/1 [==============================] - 0s 16ms/step - loss: 12676163584.0000 - mean_absolute_error: 105725.6641
Epoch 9/20

### Predicting the results of the Test set

In [22]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 [==============================] - 0s 149ms/step
[[105885.77 103282.48]
 [115638.3  144259.5 ]
 [114132.55 146122.05]
 [ 69104.4   77798.93]
 [184046.09 191050.49]
 [149073.08 105008.41]
 [ 75114.34  81229.16]
 [ 89047.55  97483.66]
 [129669.66 110352.35]
 [165903.33 166188.04]]
